### ISSUE TITLE
Incorrect text wrapping for internal and external comment fields.

### ISSUE THREAD

**Issue by ben133290** [dbisUnibas/CS108-PET#33]
The text areas in the evaluator used by tutors for the external and internal comments don't wrap text correctly. This can be annoying when writing a longer comment. 

I was able to fix the issue locally by adding the two missing lines to ProgressSummaryScene.java, but I don't have the permissions to push my bugfix branch to the remote repository.

**Comment by sauterl** [comment]
Thanks for the issue and the fixing work you have done. Could you please, if you did not already create a fork and file for a Pull Request?
